name: Build and Distribute Multi-Platform Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Tauri App on Multiple Platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Set up OS dependencies
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev libgtk-3-dev

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri App
      run: cargo tauri build --release

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: tauri-app-${{ runner.os }}
        path: target/release/bundle/
