name: 'MacOS Build and Distribute'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      RUST_BACKTRACE: 1
      NODE_ENV: production
      TAURI_SKIP_DEVSERVER: true

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Rust environment
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Install Node.js for Next.js frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache Node.js dependencies
      - name: Cache Node.js Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install
          cd src-tauri
          cargo update && cargo build --release
          cd ..

      # Build the Tauri application
      - name: Build Tauri App
        run: npm run tauri build

      # Upload the built artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app-macos
          path: src-tauri/target/release/bundle/macos/*.app

      # Verify the application
      - name: Verify Build
        run: |
          if [ ! -d "src-tauri/target/release/bundle/macos/*.app" ]; then
            echo "Build failed, application not found."
            exit 1
          fi
